sudo: required
services:
    - docker
before_install:
    - docker build -t encachram/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true encachram/docker-react npm run test

deploy:
    provider: elasticbeanstalk
    region: "us-east-2"
    app: "Dockerreact"
    env: "Dockerreact-env"
    bucket_name: "elasticbeanstalk-us-east-2-884944190604"
    bucket_path: "Dockerreact"
    on:
        branch: master
    access_key_id: docker-react-user
    secret_access_key: $AWS_SECRET_KEY